#Модуль с генератором ссылок

categories = {"Мода и стиль": 'moda-i-stil/', 
			  "Хобби, отдых и спорт": 'hobbi-otdyh-i-sport/', 
			  "Недвижимость": 'nedvizhimost/', 
			  "Детский мир": 'detskiy-mir/', 
			  "Животные": 'zhivotnye/', 
			  "Электроника": 'elektronika/', 
			  "Транспорт": 'transport/'}

subcategories = {"Одежда/обувь": 'odezhda/', 
				 "Аксессуары": 'aksessuary/', 
				 "Красота и здоровье": 'krasota-zdorove/', 
				 "Для свадьбы": 'dlya-svadby/', 
				 "Наручные часы": 'naruchnye-chasy/', 
				 "Подарки": 'podarki/', 
				 "Мода разное": 'moda-raznoe/',
				 "Антиквариат/коллекции": 'antikvariat-kollektsii/', 
				 "Книги/журналы": 'knigi-zhurnaly/', 
				 "Спорт/отдых": 'sport-otdyh/', 
				 "CD/DVD/пластинки/кассеты": 'cd-dvd-plastinki/', 
				 "Музыкальные инструменты": 'muzykalnye-instrumenty/', 
				 "Другое": 'drugoe/', 
				 "Билеты": 'bilety/',
				 "Квартиры, комнаты": 'kvartiry-komnaty/', 
				 "Коммерческая недвижимость": 'kommercheskaya-nedvizhimost/', 
				 "Предложения от застройщиков": 'predlozheniya-ot-zastroyshchikov/', 
				 "Дома": 'doma/', 
				 "Гаражи/парковки": 'garazhy-parkovki/', 
				 "Недвижимость за рубежом": 'nedvizhimost-za-rubezhom/', 
				 "Земля": 'zemlya/', 
				 "Посуточная аренда жилья": 'posutochno-pochasovo/',
				 "Детская одежда": 'detskaya-odezhda/', 
				 "Детские автокресла": 'detskie-avtokresla/', 
				 "Детский транспорт": 'detskiy-transport/', 
				 "Прочие детские товары": 'prochie-detskie-tovary/', 
				 "Детская обувь": 'detskaya-obuv/', 
				 "Детская мебель": 'detskaya-mebel/', 
				 "Кормление": 'kormlenie/', 
				 "Детские коляски": 'detskie-kolyaski/', 
				 "Игрушки": 'igrushki/', 
				 "Товары для школьников": 'tovary-dlya-shkolnikov/',
				 "Собаки": 'sobaki/', 
				 "Товары для животных": 'tovary-dlya-zhivotnyh/', 
				 "Сельхоз животные": 'selskohozyaystvennye-zhivotnye/', 
				 "Кошки": 'koshki/', 
				 "Бесплатно(животные и вязка)": 'besplatno-zhivotnye-i-vyazka/', 
				 "Аквариумные рыбки": 'akvariumnye-rybki/', 
				 "Вязка": 'vyazka/', 
				 "Птицы": 'ptitsy/', 
				 "Другие животные": 'drugie-zhivotnye/', 
				 "Грызуны": 'gryzuny/', 
				 "Рептилии": 'reptilii/',
				 "Телефоны и аксессуары": 'telefony-i-aksesuary/', 
				 "Компьютеры и комплектующие": 'kompyutery-i-komplektuyuschie/', 
				 "ТВ/видеотехника": 'tv-videotehnika/', 
				 "Техника для кухни": 'tehnika-dlya-kuhni/', 
				 "Аудиотехника": 'audiotehnika/', 
				 "Техника для дома": 'tehnika-dlya-doma/', 
				 "Фото/видео": 'foto-video/', 
				 "Ноутбуки и аксессуары": 'noutbuki-i-aksesuary/', 
				 "Аксессуары и комплектующие": 'aksessuary-i-komplektuyuschie/', 
				 "Индивидуальный уход": 'individualnyy-uhod/', 
				 "Прочая электроника": 'prochaja-electronika/', 
				 "Игры и игровые приставки": 'igry-i-igrovye-pristavki/', 
				 "Планшеты/эл. книги и аксессуары": 'planshety-el-knigi-i-aksessuary/', 
				 "Климатическое оборудование": 'klimaticheskoe-oborudovanie/',
				 "Легковые автомобили": 'legkovye-avtomobili/', 
				 "Грузовые автомобили": 'gruzovye-avtomobili/', 
				 "Автобусы": 'avtobusy/', 
				 "Мото": 'moto/', 
				 "Спецтехника": 'spetstehnika/', 
				 "Сельхоз техника": 'selhoztehnika/', 
				 "Водный транспорт": 'vodnyy-transport/', 
				 "Прицепы/Дома на колёсах": 'pritsepy-doma-na-kolesah/', 
				 "Воздушный транспорт": 'vozdushnyy-transport/', 
				 "Другой транспорт": 'drugoy-transport/'}

sections = {"Женская одежда": 'zhenskaya-odezhda/', 
			"Женская обувь": 'zhenskaya-obuv/', 
			"Мужская одежда": 'muzhskaya-odezhda/', 
			"Мужская обувь": 'muzhskaya-obuv/',
		   "Женское белье/купальники": 'zhenskoe-bele-kupalniki/', 
		   "Головные уборы": 'golovnye-ubory/', 
		   "Одежда для беременных": 'odezhda-dlya-beremennyh/', 
		   "Мужское белье": 'muzhskoe-bele/',
		   "Сумки": 'sumki/', 
		   "Другие аксессуары": 'drugie-aksessuary/', 
		   "Бижутерия": 'bizhuteriya/', 
		   "Ювелирные изделия": 'yuvelirnye-izdeliya/',
		   "Прочие товары": 'prochie-tovary-dlya-krasoty-i-zdorovya/', 
		   "Парфюмерия": 'parfyumeriya/', 
		   "Косметика": 'kosmetika/', 
		   "Средства по уходу": 'sredstva-po-uhodu/', 
		   "Оборудование парикмахерских/салонов красоты": 'oborudovanie-parikmaherskih-salonov-krasoty/', 
		   "Товары для инвалидов": 'tovary-dlya-invalidov/',
		   "Свадебные платья": 'svadebnye-platya/', 
		   "Свадебные аксессуары": 'svadebnye-aksessuary/',
		   "Коллекционирование": 'kollektsionirovanie/', 
		   "Поделки/рукоделие": 'podelki-rukodelie/', 
		   "Живопись": 'zhivopis/', 
		   "Букинистика": 'bukinistika/', 
		   "Предметы искусства": 'predmety-iskusstva/', 
		   "Антикварная мебель": 'antikvarnaya-mebel/',
		   "Вело": 'velo/', 
		   "Атлетика/фитнес": '/atletika-fitnes', 
		   "Охота/рыбалка": 'ohota-rybalka/', 
		   "Туризм": 'turizm/', 
		   "Прочие виды спорта": 'prochie-vidy-sporta/', 
		   "Футбол": 'futbol/', 
		   "Роликовые коньки": 'rolikovye-konki/', 
		   "Настольные игры": 'nastolnye-igry/', 
		   "Единоборства/бокс": 'edinoborstva-boks/', 
		   "Лыжи/сноуборды": 'lyzhi-snoubordy/', 
		   "Водные виды спорта": 'vodnye-vidy-sporta/', 
		   "Коньки": 'konki/', 
		   "Игры с ракеткой": 'igry-s-raketkoy/', 
		   "Хоккей": 'hokkey/',
		   "Студийное оборудование": 'studiynoe-oborudovanie/', 
		   "Аксессуары для музыкальных интрументов": 'aksessuary-dlya-muzykalnyh-instrumentov/', 
		   "Прочее": 'prochee/', 
		   "Пианино, фортепиано, рояли": 'pianino-fortepiano-royali/', 
		   "Духовые инструменты": 'duhovye-instrumenty/', 
		   "Акустические гитары": 'akusticheskie-gitary/', 
		   "Электрогитары": 'elektrogitary/', 
		   "Синтезаторы": 'sintezatory/', 
		   "Ударные интрументы": 'udarnye-instrumenty/', 
		   "Комбоусилители": 'kombousiliteli/', 
		   "Бас гитары": 'bas-gitary/',
		   "Продажа квартир, комнат": 'prodazha-kvartir-komnat/', 
		   "Аренда квартир, комнат": 'arenda-kvartir-komnat/',
		   "Аренда коммерческой недвижимости": 'arenda-kommercheskoy-nedvizhimosti/', 
		   "Продажа коммерческой недвижимости": 'prodazha-kommercheskoy-nedvizhimosti/',
		   "Продажа домов": 'prodazha-domov/', 
		   "Аренда домов": 'arenda-domov/',
		   "Продажа гаражей/парковок": 'prodazha-garazhey-parkovok/', 
		   "Аренда гаражей/парковок": 'arenda-garazhey-parkovok/',
		   "Продажа земли": 'prodazha-zemli/', 
		   "Аренда земли": 'arenda-zemli/',
		   "Квартиры": 'posutochno-pochasovo-kvartiry/', 
		   "Дома": 'posutochno-pochasovo-doma/', 
		   "Хостелы": 'posutochno-pochasovo-khostely/', 
		   "Комнаты": 'posutochno-pochasovo-komnaty/', 
		   "Отели": 'posutochno-pochasovo-oteli/',
		   "Для мальчиков": 'odezhda-dlya-malchikov/', 
		   "Для девочек": 'odezhda-dlya-devochek/', 
		   "Для новорожденных": 'odezhda-dlya-novorozhdennyh/',
		   "Мобильные телефоны/смартфоны": 'mobilnye-telefony-smartfony/', 
		   "Аксессуары для телефонов": 'aksessuary-dlya-telefonov/', 
		   "Стационарные телефоны": 'statsionarnye-telefony/',
		  "Запчасти для телефонов": 'zapchasti-dlya-telefonov/', 
		  "Рации и прочие телефоны": 'ratsiyi-i-prochie-telefony/', 
		  "Симкарты, тарифы, номера": 'sim-karty-tarify-nomera/',
		  "Комплектующие и аксессуары": 'komplektuyuschie-i-aksesuary/', 
		  "Периферийные устройства": 'periferiynye-ustroystva/', 
		  "Настольные компьютеры": 'nastolnye-kompyutery/', 
		  "Мониторы": 'monitory/', 
		  "Расходные материалы": 'rashodnye-materialy/', 
		  "Внешние накопители": 'vneshnie-nakopiteli/', 
		  "Другое": 'drugoe/', 
		  "Серверы": 'servery/',
		  "Телевизоры": 'televizory/', 
		  "Аксессуары для ТВ и видеотехники": 'aksessuary-dlya-tv-videotehniki/', 
		  "Прочая ТВ, видеотехника": 'prochaya-tv-videotehnika/', 
		  "DVD плееры": 'dvd-pleery/', 
		  "Спутниковое ТВ": 'sputnikovoe-tv/', 
		  "Проекторы": 'proektory/',
		  "Прочая техника для кухни": 'prochaya-tehnika-dlya-kuhni/', 
		  "Холодильники": 'holodilniki/', 
		  "Плиты/печи": 'plity-pechi/', 
		  "Кофеварки/кофемолки": 'kofevarki-kofemolki/', 
		  "Кухонные комбайны и измельчители": 'kuhonnye-kombayny-i-izmelchiteli/', 
		  "Пароварки": 'parovarki/', 
		  "Электрочайники": 'elektrochayniki/', 
		  "Микроволновые печи": 'mikrovolnovye-pechi/', 
		  "Посудомоечные машины": 'posudomoechnye-mashiny/', 
		  "Хлебопечки": 'hlebopechki/', 
		  "Вытяжки": 'vytyazhki/',
		  "Наушники": 'naushniki/', 
		  "Акустические системы": 'akusticheskie-sistemy/', 
		  "Портативная акустика": 'portativnaya-akustika/', 
		  "Прочая аудиотехника": 'prochaya-audiotehnika/', 
		  "Усилители/ресиверы": 'usiliteli-resivery/', 
		  "Радиоприемники": 'radiopriemniki/', 
		  "Магнитолы": 'magnitoly/', 
		  "Музикальные центры": 'muzykalnye-tsentry/', 
		  "CD/MD/виниловые проигрыватели": 'cd-md-vinilovye-proigryvateli/', 
		  "MP3 плееры": 'mp3-pleery/',
		  "Стиральные машины": 'stiralnye-mashiny/', 
		  "Прочая техника для дома": 'prochaya-tehnika-dlya-doma/', 
		  "Швейные машины и оверлоки": 'shveynye-mashiny-i-overloki/', 
		  "Пылесосы": 'pylesosy/', 
		  "Утюги": 'utyugi/', 
		  "Фильтры для воды": 'filtry-dlya-vody/', 
		  "Вязальные машины": 'vyazalnye-mashiny/',
		  "Цифровые фотоапарраты": 'tsifrovye-fotoapparaty/', 
		  "Аксессуары для фото/видеокамер": 'aksessuary-dlya-foto-videokamer/', 
		  "Пленочные фотоапарраты": 'plenochnye-fotoapparaty/', 
		  "Видеокамеры": 'videokamery/', 
		  "Объективы": 'obektivy/', 
		  "Экшн-камеры": 'ekshn-kamery/', 
		  "Телескопы/бинокли": 'teleskopy-binokli', 
		  "Штативы/монопады": 'shtativy-monopody/', 
		  "Фотовспышки": 'fotovspyshki/',
		  "Ноутбуки": 'noutbuki/', 
		  "Запчасти для ноутбуков": 'zapchasti-dlya-noutbukov/', 
		  "Аксессуары для ноутбуков": 'aksessuary-dlya-noutbukov/',
		  "Электронные сигареты, вапорайзеры и аксессуары": 'elektronnye-sigarety-vaporaizery-i-aksessuary/', 
		  "Фены, укладка волос": 'feny-ukladka-volos/', 
		  "Прочая техника для индивидуального ухода": 'prochaya-tehnika-dlya-individualnogo-uhoda/', 
		  "Бритвы, эпиляторы, машинки для стрижки": 'britvy-epilyatory-mashinki-dlya-strizhki/', 
		  "Весы": 'vesy/',
		  "Игры для приставок": 'igry-dlya-pristavok/', 
		  "Приставки": 'pristavki/', 
		  "Аксессуары": 'aksessuary/', 
		  "Герои игр": 'geroi-igr/', 
		  "Игры для ПК": 'igry-dlya-pc/',
		  "Планшетные компьютеры": 'planshetnye-kompyutery/', 
		  "Аксессуары для планшетов, эл. книг": 'aksessuary-dlya-planshetov-el-knig/', 
		  "Запчасти для планшетов, эл. книг": 'zapchasti-dlya-planshetov-el-knig/',
		  "Электронные книги": 'elektronnye-knigi/',
		  "Графические планшеты": 'graficheskiye-planshety/'}

subsections = {"Прочие комплектующие": 'prochie-komplektuyuschie/',
			"Видеокарты": 'videokarty/',
			"Жесткие диски": 'zhestkie-diski/',
			"Процессоры": 'protsessory/',
			"Модули памяти": 'moduli-pamyati/',
			"Материнские платы": 'materinskie-platy/',
			"Корпуса": 'korpusa/',
			"Блоки питания": 'bloki-pitaniya/',
			"Оптические диски": 'opticheskie-privody/',
			"ТВ-тюнеры": 'tv-tyunery/',
			"Копиры": 'kopiry/',
			"Сетевое оборудование": 'setevoe-oborudovanie/',
			"Прочие периферийные устройства": 'prochie-periferiynye-ustroystva/',
			"Клавиатуры, мыши, манипуляторы": 'klaviatury-myshi-manipulyatory/',
			"Вебкамеры": 'vebkamery/',
			"Компьтерная акустика": 'kompyuternaya-akustika/',
			"Принтеры": 'printery/',
			"МФУ": 'mfu/',
			"Сканеры": 'skanery/'}

def get_way(index_category, index_subcategory, index_section, index_subsection, request):

	base_url = 'https://www.olx.ua/'

	category = categories[index_category]
	subcategory = subcategories[index_subcategory]
	
	try:
		section = sections[index_section]
	except:
		section = ''
	
	try:
		subsection = subsections[index_subsection]
	except:
		subsection = ''
	
	request = 'q-' + request.replace(' ', '-') + '/'

	url = base_url + category + subcategory + section + subsection + request

	return url

